### ISSUE TITLE
I can't build this project, please help..

### ISSUE THREAD

**Issue by klugev303** [Bunicutz/ESP32_Midea_RS485#11]
Please tell me what is wrong, why I can not compile this project?
![изображение](https://github.com/Bunicutz/ESP32_Midea_RS485/assets/19494749/911058e2-e1a7-4f78-ab5f-705bd5a6f3fb)
do I need to remove the "#" in the file bunicutz_AC.h ?
![изображение](https://github.com/Bunicutz/ESP32_Midea_RS485/assets/19494749/5da60b0c-f724-4672-97ff-5aec9faf8507)
(yaml and bunicutz_AC.h in the attachment ZIP file)
[esphome.zip](https://github.com/Bunicutz/ESP32_Midea_RS485/files/12519560/esphome.zip)

**Comment by Flachzange** [comment]
It seems you  are compiling against ESP8266 libs and not ESP32 because of your board type:

`board: esp01_1m`

**Comment by klugev303** [comment]
I have board "_**NodeMcu V3**_"
Can't I use this one?
Tell me with what board then it works, I'll order then, thanks!

**Comment by klugev303** [comment]
I tried changing the board type to **_nodemcuv2_**
![изображение](https://github.com/Bunicutz/ESP32_Midea_RS485/assets/19494749/9fa90b17-17d8-40bf-96db-a2ecbbd09cc2)

But the build also stopped with an error
![изображение](https://github.com/Bunicutz/ESP32_Midea_RS485/assets/19494749/410d1a08-004d-468d-bd46-7458db3e7494)

**Comment by Flachzange** [comment]
The NodeMCU V3 seems to be an ESP8266 board. You would need an ESP32 board, e.g. ESP32 NodeMCU

**Comment by klugev303** [comment]
would this fit?

![изображение](https://github.com/Bunicutz/ESP32_Midea_RS485/assets/19494749/c9bc0b58-073d-4aae-a3ef-14e3847a49f8)

**Comment by Flachzange** [comment]
yes, looks good. Be aware that you also need the RS485 adapter in case you don't have it yet (see other issue ticket)

**Comment by klugev303** [comment]
adapter RS485 that TTL in the order, I'm waiting already. And tell me, are there any other boards **_ESP-WROOM-32D_**  will they also fit? They are cheaper

**Comment by Flachzange** [comment]
Probably any ESP32 will do the trick, but remember that you need to be able to programme it, i.e. you would need a usb connection.

**Comment by klugev303** [comment]
Can be flashed through "ESP flasher"  ?

**Comment by Flachzange** [comment]
I don't know what ESP flasher is, sorry

**Comment by klugev303** [comment]
Thank you very much for your help!
