### ISSUE TITLE
General questions

### ISSUE THREAD

**Issue by ralf-e** [Bunicutz/ESP32_Midea_RS485#2]
Hello,
is there any more detailed information about this?
What AC are you using this on (VRF)?
Only on individual indoor devices or also to control multiple IDUs that are connected via the XYE bus?
Or would that also work like the Midea central controls with a connection to the XYE port on the outdoor unit in VRF or Mini-VRF systems?
regrades, Ralf

**Comment by Bunicutz** [comment]
Hello,

I have just implemented the reverse engineered com protocol from xye ( https://codeberg.org/xye/xye ) and integrated it with HA . 

I have a Zephir duct AC (one internal and one external units not sure if it is or not a VRF) which is a copy of  Midea.

My setup is connected to the single indoor unit I have. I did not consider more Indoor units. For the outdoor unit I understood that there is a similar port with XYE but I do not know if the communication protocol is the same.

As I understand/view it tis is similar to a CCM18 ( https://www.orient-hvac.com/product/Modbus-BMS-gateway-CCM-18A.html ) but a gateway for HA. 
You could try to instantiate the class for each unit you have and connect them all to the same bus. Theoretically it should work but I never tied it and you have to get the addresses sorted out for the units. 

BR, B
