### ISSUE TITLE
General question

### ISSUE THREAD

**Issue by TimoSEL** [Bunicutz/ESP32_Midea_RS485#3]
is it possible to start the outdoor unit without an indoor unit? can you help?

**Comment by Bunicutz** [comment]
this com protocol is between the ESP and the indoor unit. the indoor unit later on requests the outdoor unit to start.
If you would like to do that you have to crack the S1 S2 com protocol which is the protocol between the indoor and outdoor units.
Unfortunately I can not do that on my side.
