### ISSUE TITLE
Use another RS485-TTL module Maybe we could connect without DE/RE

### ISSUE THREAD

**Issue by phoenixxie0** [Bunicutz/ESP32_Midea_RS485#4]
I have found a RS485-TTL module that use the AutoDirection. And it product with MAX13487. So I think we can use it to connect without RE/DE. And It can free two GPIO point.
[https://item.taobao.com/item.htm?spm=a230r.1.14.40.1b2340a7xfdnD0](url)

**Comment by Bunicutz** [comment]
It would only free one because on the master side the RE/DE are connected together. 
![image](https://user-images.githubusercontent.com/99245025/188263544-5de4236f-15b0-40a1-80c7-bc3f1759d594.png)
But yes. that would be cool

**Comment by phoenixxie0** [comment]
THX. And I will have a try. I also found a board named DT-06 witch make with ESP8266. And it have only TX RX STATE GND VCC. So It is very small, and it can make the module smaller that while it connect to MAX13487.
[https://item.taobao.com/item.htm?spm=a230r.1.14.13.639927f77gxvdQ](url)
![ DT-06](https://img.alicdn.com/imgextra/i1/3459570602/TB2i9LdXkfb_uJkHFqDXXXVIVXa_!!3459570602.jpg)

**Comment by Bunicutz** [comment]
Ok. But my code is for ESP32. On ESP8266 you have to do some modifications. Please have a look on closed issues to see more details.
