### ISSUE TITLE
Query's response

### ISSUE THREAD

**Issue by ghost** [Bunicutz/ESP32_Midea_RS485#5]
Good job.

I don't know if you can help me. I'm trying to connect my Midea with an ELFIN EW11 (I'm at the beginning), I see that the hardware part is resolved and it communicates with the machine, but I always get an error message. (or does not respond)

I have tried different ways to send the query and it always responds the same.

Could it be that the machine  has another communication system implemented?

Would you have some examples of queries that work?

this is a status query and its response (whatever you do always returns the same thing)

008-Tx:AA C0 00 02 80 02 00 00 00 00 00 00 00 3F D3 55
009-Rx:AA C0 80 02 00 02 00 00 00 00 00 FF FF FF FF FF FF FF FF 00 00 00 00 00 00 00 02 FF 00 00 C3 55

thank's

**Comment by Bunicutz** [comment]
Hi.

I am not sure (haven't worked on this in a while) but I guess the CRC might be wrong.
Here is a command that the AC responds fine for me: aa c0 0 0 80 0 0 0 0 0 0 0 0 3f 81 55

**Comment by ghost** [comment]
thank you.

yes, that was it, it did not include the last number
