### ISSUE TITLE
master and slave ID

### ISSUE THREAD

**Issue by Cosmicbase** [Bunicutz/ESP32_Midea_RS485#6]
Hello, where can I get the master and slave ID from?

I have to adjust the bunicutz_AC.h?

#define SERIAL_COM_MASTER_ID 0 
#define SERIAL_COM_SLAVE_ID 0

**Comment by Bunicutz** [comment]
In principle if you have one internal and one external it should be ok both0. Otherwize you should try out different combinations until it works.
